# -*- coding: utf-8 -*-
"""Neural_prophet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xGt1f6QR2EsEB_y3nNbjTNKdH7d8_JZ

Neural Prophet
"""

!pip uninstall -y torch notebook notebook_shim tensorflow tensorflow-datasets prophet torchaudio torchdata torchtext torchvision

!pip install git+https://github.com/ourownstory/neural_prophet.git

import pandas as pd
import yfinance as yf

from neuralprophet import NeuralProphet, set_log_level

df = yf.download("AAPL", start="2016-01-01", end="2024-01-01", auto_adjust=False, multi_level_index=False)

df = df["Close"]

df = df.reset_index()

df = df.rename(columns = {"Date":"ds", "Close":"y"})

plt = df.plot(x="ds", y="y", figsize=(12, 6))

set_log_level("ERROR")

m = NeuralProphet()

m.set_plotting_backend("plotly-static")

metrics = m.fit(df)

df_future = m.make_future_dataframe(df, n_historic_predictions=True, periods=365)

forecast = m.predict(df_future)

m.plot(forecast)

m.plot_parameters(components=["trend", "seasonality"])

